// Guia Editorial e Criativo VendaMais Content v1.0 (16/09/2026). Linha editorial obrigatória dos três posts.
// Fonte: uploads/Guia_Editorial_VendaMais_Content.docx. Editável no Brand Center → Linha editorial.
export const EDITORIAL_GUIDE_V1 = {
  version: 1, updated_at: '2026-09-16',
  principle: 'Uma newsletter. Três interpretações. Três públicos. Os posts compartilham a origem, mas não podem parecer três versões do mesmo texto. Não resumir nem recortar a newsletter.',
  reading: ['tese central', 'tensão ou problema de negócio', 'insight mais relevante', 'mudança de perspectiva proposta', 'consequências para a empresa', 'trechos com maior poder de provocar reflexão'],
  angles: {
    training: { label: 'BU Treinamentos', audience: 'Gerentes e líderes de RH, T&D, DHO, Desenvolvimento Organizacional, executivos responsáveis por capacitação e desenvolvimento de lideranças e equipes', question: 'O que este tema revela sobre a capacidade da empresa de desenvolver pessoas e transformar comportamento comercial?', tension: 'Capacitação x aplicação', outcome: 'Interesse em desenvolvimento', cta: 'Reflexão sobre desenvolvimento', prefer: ['gap entre treinamento e execução', 'mudança de comportamento', 'desenvolvimento de lideranças', 'aplicação prática', 'aprendizagem contínua', 'aderência do conteúdo à realidade comercial', 'preparação de equipes para novos desafios', 'como medir se uma capacitação virou ação'], avoid: ['falar diretamente com o vendedor como público principal', 'reduzir treinamento a evento, palestra ou dia de capacitação', 'vender curso no primeiro parágrafo', 'prometer transformação sem explicar o mecanismo'] },
    consulting: { label: 'BU Consultoria', audience: 'CEOs, diretores comerciais, gerentes comerciais, executivos responsáveis por crescimento, receita e performance', question: 'O que este tema revela sobre a forma como a empresa está sendo gerida comercialmente?', tension: 'Sintoma x causa de gestão', outcome: 'Interesse em transformação ou diagnóstico', cta: 'Reflexão sobre gestão', prefer: ['previsibilidade', 'produtividade', 'gestão de carteira', 'estratégia comercial', 'processos', 'indicadores', 'liderança', 'execução', 'governança', 'qualidade das decisões', 'gargalos invisíveis', 'diferença entre sintomas e causas'], avoid: ['linguagem de dica para vendedor', 'conteúdo excessivamente operacional', 'fórmulas simplistas para problemas complexos', 'vender consultoria antes de construir o problema e o ponto de vista'] },
    business: { label: 'VendaMais Institucional', audience: 'Executivos e decisores B2B, lideranças comerciais, RH/DHO, profissionais que influenciam decisões de desenvolvimento ou transformação comercial, mercado empresarial', question: 'Que ponto de vista a VendaMais quer ocupar na cabeça do mercado sobre este assunto?', tension: 'Prática antiga x nova realidade', outcome: 'Autoridade e lembrança de marca', cta: 'Conversa ou aprofundamento', prefer: ['leitura de mercado', 'mudança de comportamento das empresas', 'tensões contemporâneas da gestão comercial', 'evolução da função de vendas', 'decisões que diferenciam empresas maduras', 'conceitos ou provocações proprietárias', 'visão estratégica sobre performance comercial'], avoid: ['ficar limitado a uma BU', 'autoelogio', 'propaganda'] } },
  voice: { traits: ['Direta: chega ao ponto, sem introdução longa', 'Pragmática: conecta conceito a decisões reais de gestão', 'Provocadora: questiona crenças sem agressividade ou superioridade', 'Madura: fala com executivos como pares, não promete milagres', 'Humana: reconhece dilemas, pressões e comportamentos reais', 'Segura: demonstra experiência sem afirmar que é especialista'],
    do: ['O problema pode não estar na habilidade do time. Pode estar no sistema que deveria sustentar a execução.', 'Quando todo forecast depende da percepção individual de cada vendedor, a empresa não tem previsão. Tem opinião.', 'Treinamento não falha apenas porque o conteúdo foi ruim. Muitas vezes ele falha porque a rotina volta ao normal na segunda-feira.', 'Há empresas tentando corrigir com cobrança aquilo que nasceu de um problema de processo.'],
    dont: ['5 dicas infalíveis para vender mais.', 'Você está pronto para revolucionar suas vendas?', 'O segredo que ninguém te contou.', 'Sua equipe nunca mais será a mesma.', 'Nós somos líderes e especialistas em transformar empresas.', 'Com nossa metodologia exclusiva, garantimos resultados extraordinários.'] },
  evidence: { rule: 'Nunca inventar case, cliente, percentual, resultado, pesquisa ou dado. Casos reais com número são bem-vindos quando validados, mas não são obrigatórios.', fallback: ['situações recorrentes no cotidiano das empresas', 'dilemas típicos de gestão', 'comportamentos observáveis', 'perguntas que revelem contradições', 'cenários hipotéticos claramente tratados como exemplo'], safe_phrases: ['É comum encontrar empresas em que...', 'Uma situação recorrente é...', 'Muitos gestores convivem com...', 'Imagine uma empresa em que...', 'Na prática, o problema aparece quando...'] },
  narrative: ['Tensão: contradição, problema ou situação reconhecível', 'Reenquadramento: a causa pode ser diferente da que se imagina', 'Insight: o ponto de vista central', 'Consequência: por que importa para este público', 'Provocação ou ação: pergunta, decisão, reflexão ou convite leve'],
  cta: { prefer: ['Vale olhar para isso na sua operação.', 'Talvez a pergunta não seja X. Talvez seja Y.', 'Como isso acontece hoje na sua empresa?', 'Esse é um bom tema para levar à próxima reunião de gestão.', 'Se esse problema aparece na sua operação, vale conversar.'], avoid: ['Compre agora.', 'Clique e contrate.', 'Não perca essa oportunidade.', 'Fale conosco hoje mesmo e transforme seus resultados.'] },
  visual: { avoid: ['todos os posts com a mesma moldura', 'título central + bloco de texto + logo no mesmo lugar', 'excesso de caixas e cards', 'visual corporativo genérico', 'banco de imagens com poses artificiais', 'carrossel por padrão', 'colocar na arte tudo que já está na legenda', 'elementos gráficos só para preencher espaço'], seek: ['hierarquia visual forte', 'espaço negativo', 'composições assimétricas', 'tipografia como elemento criativo', 'fotografia editorial e humana', 'recortes e escala que criem tensão', 'diagramas só quando agregam entendimento', 'alternância entre peças densas e minimalistas'], feeling: 'Consultoria premium + inteligência comercial + publicação editorial contemporânea.',
    photo_direction: 'Fotografia editorial de campanha, padrão estúdio: luz direcional, 85mm, profundidade rasa, grão fino, paleta dessaturada em azul-petróleo e neutros quentes. Um sujeito por imagem: um único profissional em ação real (sério, concentrado, nunca sorrindo para a câmera, de perfil, de costas ou parcialmente fora de foco) ou cena sem pessoas (mesa de decisão com relatório, quadro de indicadores desfocado, corredor de indústria, tela de CRM fora de foco, mãos em detalhe). Proibido: grupos posados, três ou mais rostos, aperto de mão, sorriso de banco de imagens, rosto plastificado. Expressão e cena obedecem ao tom do post (tensão, diagnóstico, decisão).',
    formats: { typographic: 'uma ideia forte: peça tipográfica (T04)', photo: 'situação humana ou executiva: fotografia editorial + headline (T01, T03)', data: 'dado validado: visual de dados (T02, T04 com número)', carousel: 'raciocínio progressivo, antes/depois, diagnóstico em camadas, framework: carrossel', contrast: 'contraste: composição que evidencie oposição (T03)' }, rule: 'Se uma ideia cabe em uma peça, não transformá-la em sete slides. Evitar repetição visual consecutiva: considerar os formatos das últimas peças.' },
  art_text: 'A arte não reproduz a legenda. Preferir headline forte, frase curta, conceito, pergunta ou dado validado. A legenda desenvolve o raciocínio.',
  quality_gate: ['puder ser publicada por qualquer consultoria sem mudança relevante', 'parecer conteúdo genérico de IA', 'não tiver tese ou tensão clara', 'depender de case inexistente', 'falar com vendedores quando o público é executivo ou RH', 'usar dado sem fonte', 'transformar a VendaMais em protagonista antes do problema do cliente', 'ter mais design do que ideia', 'repetir mecanicamente uma estrutura anterior', 'usar carrossel sem necessidade'],
  self_critique: ['a ideia é específica ou genérica?', 'poderia ser de qualquer consultoria?', 'existe algum clichê?', 'foi inventado algum dado?', 'fala realmente com o público definido?', 'o formato foi escolhido pela ideia?', 'há excesso de texto na arte?', 'os três posts são suficientemente diferentes entre si?', 'o conjunto eleva a percepção da marca VendaMais?'],
  signature: 'A VendaMais enxerga os problemas comerciais além da superfície, transforma situações comuns em boas perguntas de gestão e oferece caminhos aplicáveis sem simplificar demais a realidade.'
};
export function guideForPrompt(g = EDITORIAL_GUIDE_V1, recentFormats = []) {
  const A = g.angles;
  return `LINHA EDITORIAL VENDAMAIS CONTENT (obrigatória)
${g.principle}
ETAPA 1, leitura editorial: identifique ${g.reading.join('; ')}.
ETAPA 2, três interpretações independentes:
1) training = ${A.training.label}. Público: ${A.training.audience}. Pergunta: ${A.training.question} Tensão: ${A.training.tension}. Ângulos: ${A.training.prefer.join(', ')}. Evitar: ${A.training.avoid.join('; ')}. CTA: ${A.training.cta}.
2) consulting = ${A.consulting.label}. Público: ${A.consulting.audience}. Pergunta: ${A.consulting.question} Tensão: ${A.consulting.tension}. Ângulos: ${A.consulting.prefer.join(', ')}. Evitar: ${A.consulting.avoid.join('; ')}. CTA: ${A.consulting.cta}.
3) business = ${A.business.label}. Público: ${A.business.audience}. Pergunta: ${A.business.question} Tensão: ${A.business.tension}. Ângulos: ${A.business.prefer.join(', ')}. Evitar: ${A.business.avoid.join('; ')}. CTA: ${A.business.cta}.
VOZ: ${g.voice.traits.join(' | ')}
Exemplos do tom certo: ${g.voice.do.map(s => `"${s}"`).join(' ')}
Nunca assim: ${g.voice.dont.map(s => `"${s}"`).join(' ')}
EVIDÊNCIAS: ${g.evidence.rule} Sem dado, use ${g.evidence.fallback.join(', ')}; frases seguras: ${g.evidence.safe_phrases.join(' / ')}
ESTRUTURA (referência, não fórmula): ${g.narrative.join(' > ')}
CTA leve. Preferir: ${g.cta.prefer.join(' / ')}. Nunca: ${g.cta.avoid.join(' / ')}
FORMATO nasce da ideia: ${Object.values(g.visual.formats).join('; ')}. ${g.visual.rule}${recentFormats.length ? ` Formatos das últimas peças publicadas (evite repetir em sequência): ${recentFormats.join(', ')}.` : ''}
ARTE: ${g.art_text}
VISUAL, evitar: ${g.visual.avoid.join('; ')}. Buscar: ${g.visual.seek.join('; ')}. Sensação: ${g.visual.feeling}
AUTOCRÍTICA antes de responder: ${g.self_critique.join(' ')} Reprove e reescreva se: ${g.quality_gate.join('; ')}.
ASSINATURA: ${g.signature}${humanVoiceForPrompt()}`;
}

// v2 (30/09/2026): voz humana e emocional validada na Newsletter 22. Vale para todas as edições e se soma à linha editorial salva no Brand Center.
export const HUMAN_VOICE_V2 = {
  shift: 'Escreva como alguém que já esteve do outro lado da mesa, não como professor. Parta de uma cena que o gestor reconhece, nomeie a frustração em voz alta, mostre empatia com o esforço de quem tentou e só então leve à ação. Firme sem ser duro; humano sem ser motivacional.',
  do: ['Abrir com cena concreta e reconhecível (a sala cheia, a agenda lotada, o fim de expediente).', 'Nomear o sentimento real: frustração, cansaço, dúvida ("Frustrante, né?", "Se isso já aconteceu com você, você não está sozinho").', 'Tirar a culpa da pessoa e colocar no sistema ("Não por falta de vontade. Por falta de apoio.").', 'Falar em "a gente" quando a VendaMais relata o que vê no campo.', 'Ponto aplicável como gesto pequeno e humano para esta semana (uma pergunta, uma conversa), não como checklist.', 'CTA como convite: "Vamos conversar?", "Quer que o próximo treinamento fique de verdade?".'],
  avoid: ['tom de aula ou de manual ("é fundamental", "é necessário", "deve-se")', 'frases taxativas em sequência sem respiro', 'julgar o leitor ou a equipe', 'motivacional vazio, superlativo, promessa'],
  formats: 'Sequência, passo a passo ou antes/durante/depois: carrossel. Uma ideia forte que cabe numa frase: post único. Evite dois carrosséis na mesma edição; o terceiro post é único quando outro já for carrossel.',
  carousel: 'Carrossel de 6 a 7 slides: 1 capa (título da tese + apoio empático) > 2 A CENA (o que todo mundo viveu) > 3 E DEPOIS (o que deu errado, sem culpar pessoas) > 4 a 6 ação em etapas (ANTES / DURANTE / NOS 30 DIAS SEGUINTES), cada uma com título curto e texto de até 40 palavras > último: fechamento com a frase-assinatura da edição e CTA convite. Alterne fundos (navy, areia, branco). Kicker curto e em caixa alta por slide.',
  image: 'Imagem-base: fotografia editorial de estúdio, vertical 4:5, pessoas brasileiras naturais com expressão coerente com a emoção da cena (reflexiva, cansada, atenta; sorriso só quando a cena é de apoio), luz lateral quente contra sombras em azul-marinho, profundidade rasa, espaço limpo e escuro para o texto na área indicada, sem pose de banco de imagens.',
  examples: [
    { angle: 'training', headline: 'O treinamento acabou. E tudo voltou a ser como antes', hook: 'Você investiu, a equipe gostou e, semanas depois, parece que nada aconteceu. Frustrante, né?', body: 'A gente vê isso toda semana. E quase nunca é culpa do conteúdo ou da equipe. É que aprender é só o começo. Mudar um hábito leva tempo, prática e alguém por perto dizendo "continua, está funcionando".', takeaway: 'Nesta semana, escolha uma coisa que o time aprendeu e pergunte, em cada conversa: "Onde você conseguiu aplicar isso?"' },
    { angle: 'consulting', headline: 'Seu time não esqueceu o treinamento. Ele só ficou sozinho', hook: 'O vendedor voltou a fazer do jeito antigo. Antes de achar que ele não quis mudar, vale uma pergunta.', body: 'Quem estava lá com ele depois do treinamento? Na correria da operação, o gestor apaga incêndio, a meta aperta e o novo aprendizado fica para depois. Não é descaso, é sobrevivência.', takeaway: 'Na próxima reunião, troque uma pergunta sobre números por esta: "O que você tentou fazer diferente esta semana, e como foi?"' },
    { angle: 'business', headline: 'O treinamento termina na agenda. O desenvolvimento continua na operação', hook: 'Toda empresa quer ver o time evoluindo. Quase todas já sentiram que o investimento não voltou.', body: 'A gente acredita que o problema quase nunca é a pessoa. É o ambiente em volta dela. Quando RH, liderança e comercial caminham juntos, o vendedor tem espaço para tentar, errar, ajustar e crescer.', takeaway: 'Reúna RH e comercial e pergunte: "O que queremos ver diferente nas conversas com os clientes daqui a 30 dias?"' } ]
};
export const MEME_RULES = { label: 'Meme da Semana', audience: 'toda a base, para compartilhar no story e na DM', question: 'Qual cena desta semana todo gestor comercial reconhece em dois segundos?', tension: 'o leitor ri porque foi visto, não porque alguém foi exposto', cta: 'convite leve para a newsletter ou para conversar; nunca venda', prefer: ['uma cena, uma frase, legível em 2 segundos', 'vilão é o sistema: planilha, CRM, reunião, status, boleto', 'leitor como cúmplice', 'legenda curta que estende a piada e entrega uma utilidade'], avoid: ['bronca ou dedo apontado', 'rir do vendedor ou do cliente', 'gíria forçada, meme de internet, emoji em excesso', 'superlativo ou número inventado', 'texto longo na arte'] };
export function humanVoiceForPrompt(v = HUMAN_VOICE_V2) {
  return `
VOZ HUMANA (v2, obrigatória, prevalece sobre qualquer instrução de tom mais seco): ${v.shift}
Fazer: ${v.do.join(' ')}
Evitar: ${v.avoid.join('; ')}.
FORMATO: ${v.formats}
CARROSSEL: ${v.carousel}
IMAGEM (campo image_prompt): ${v.image}
EXEMPLOS APROVADOS PELO EDITOR (referência de tom e qualidade, não copie o tema):
${v.examples.map(e => `- [${e.angle}] Headline: "${e.headline}" | Gancho: "${e.hook}" | Corpo: "${e.body}" | Ponto aplicável: "${e.takeaway}"`).join('\n')}`;
}
