// Conhecimento VendaMais: portfólio, provas e territórios, extraídos do site vendamais.com.br em 11/09/2026.
// Entra como fonte institucional permanente (source_id 'kb_vendamais') em toda análise, geração e sugestão de tema.
// Editável no Brand Center. Quando o site mudar, atualize aqui primeiro.
export const KNOWLEDGE_V1 = {
  version: 1, updated_at: '2026-09-11', source_url: 'https://vendamais.com.br',
  positioning: 'O maior ecossistema de soluções para vendas da América Latina. Há mais de 30 anos, ajuda empresas a transformar desafios comerciais em método, execução e crescimento sustentável. Da estratégia à rotina comercial, vendas levadas a sério.',
  thesis: 'Vender é método, não talento isolado. Prova antes da promessa.',
  proof_numbers: [
    { id: 'P1', text: 'Mais de 2.500 clientes atendidos no Brasil e na América Latina', number: '2.500' },
    { id: 'P2', text: 'Mais de 30 anos de experiência (fundada em 1994)', number: '30' },
    { id: 'P3', text: 'Mais de 50 especialistas com vivência real de campo', number: '50' },
    { id: 'P4', text: 'Mais de 90 segmentos atendidos', number: '90' },
    { id: 'P5', text: 'Mais de 15 anos de atuação no Paraguai e América Latina', number: '15' },
    { id: 'P6', text: 'Presença em Curitiba, Foz do Iguaçu (LATAM), Jundiaí e Charlotte (EUA)', number: null } ],
  fronts: [
    { id: 'consultoria', name: 'Consultoria comercial', promise: 'Estrutura a área comercial com método, gestão e previsibilidade, do diagnóstico à execução. Menos dependência de pessoas-chave, mais previsibilidade.', offers: ['Diagnóstico Comercial', 'Planejamento Estratégico Comercial (PEC)', 'Política Comercial', 'Estratégias de Crescimento (Growth)', 'Inteligência de Mercado', 'Redesenho estratégico de portfólio', 'Inside Sales', 'Gestão de Canais de Vendas', 'Pricing', 'Aceleração Comercial Full 360º', 'Mentoria para diretoria comercial'], problems: ['Baixa previsibilidade de forecast e metas batidas no susto', 'Processo comercial informal, na cabeça de poucos', 'CRM subutilizado e decisões por achismo', 'Desconto como única ferramenta de fechamento', 'Dificuldade de escalar canais e penetrar a carteira'], audience: 'Diretoria comercial, CEOs e donos, operações comerciais estruturadas', angle: 'consulting' },
    { id: 'treinamentos', name: 'Treinamentos corporativos', promise: 'Jornadas que transformam comportamento em resultado, não eventos isolados. Conteúdo 100% aplicável, com sustentação pós-treino.', offers: ['Palestras', 'Workshops e treinamentos práticos', 'Linha Power (programas por segmento: agro, cooperativismo, farma, financeiro, construção, imobiliário, seguros, hotelaria)', 'Programas por modelo de venda (varejo, recorrente, alto valor)', 'Convenções de vendas e curadoria', 'Projetos personalizados (Sales Enablement, Jeito de Vender e de Liderar)', 'VendaMais Digital (cursos, e-books, webinários, master classes, podcast)'], problems: ['Treinamento que empolga, mas não muda comportamento', 'Conteúdo genérico, distante da realidade do time', 'Falta de prática e de sustentação depois do evento', 'Equipe que sabe o que fazer, mas não faz na rotina'], audience: 'RH, T&D, marketing e equipes comerciais com no mínimo 25 pessoas em vendas', angle: 'training' },
    { id: 'lideranca', name: 'Desenvolvimento de liderança', promise: 'Duas rotas: líderes de todas as áreas e líderes comerciais. Metas que viram rotina de execução.', offers: ['Liderança em Ação (líderes em geral)', 'Gestão Comercial em Ação (líderes comerciais)', 'Mentoria para lideranças comerciais'], problems: ['Liderança fraca', 'Meta sem rotina de gestão', 'Líder que vende mas não gere'], audience: 'Líderes e gestores comerciais', angle: 'training' },
    { id: 'games', name: 'Games corporativos', promise: 'Aprendizagem experiencial: prática, pressão e decisão que mudam indicadores.', offers: ['Vendópolis, o jogo das vendas', 'Negocialipse, negociar para sobreviver', 'Acelerador de Vendas, resultado imediato'], problems: ['Convenção que celebra mas não prepara', 'Baixo engajamento em treinamento'], audience: 'Convenções, kickoffs, jornadas de T&D', angle: 'training' },
    { id: 'bpo', name: 'BPO de gestão comercial', promise: 'Quando orientar não basta, a VendaMais assume a gestão comercial. A diretoria volta ao estratégico.', offers: ['Executivo full-time', 'Gestor de projeto', 'Comitê comercial'], problems: ['Dependência de pessoas-chave', 'Falta de gestor comercial sênior', 'Operação sem governança'], audience: 'CEOs, donos e diretorias', angle: 'business' },
    { id: 'salestrain', name: 'SalesTrain', promise: 'A IA da VendaMais para treinar vendedores todos os dias, com prática e evolução contínua.', offers: ['Simulações com IA', 'Feedback instantâneo', 'Radar de habilidades', 'Dashboard do gestor'], problems: ['Vendedor sem prática diária', 'Onboarding lento', 'Gestor sem visibilidade de habilidades'], audience: 'Times comerciais distribuídos, onboarding contínuo', angle: 'business' } ],
  methodology: { name: 'Metodologia VendaMais', steps: ['Entender: diagnóstico antes da solução; processo, gente, indicadores e contexto real', 'Desenhar: solução sob medida, não modismo', 'Compartilhar: aprender fazendo, prática e decisão que mudam comportamento', 'Sustentar: planos de ação, indicadores e acompanhamento até virar rotina'] },
  cases: [
    { id: 'C1', client: 'TIMAC Agro', segment: 'Indústria / Agro', solution: 'Sales Enablement, método "Gerar +", formação 100% digital e líderes treinadores', results: ['95% de NPS do programa', 'mais de 1.000 profissionais formados'] },
    { id: 'C2', client: 'Autotrac', segment: 'Tecnologia', solution: '"Jeito Autotrac de Vender e Liderar", jornada estruturada com game próprio', results: ['formação reduzida de 12 para 3 meses', '81% dos líderes formados'] },
    { id: 'C3', client: 'Consórcio Magalu', segment: 'Consórcios / Varejo', solution: 'Método "ENCANTAR" com jornada digital e microlearning', results: ['mais de 50% de performance', 'avaliação 4,92 de 5'] },
    { id: 'C4', client: 'Grupo Lunelli', segment: 'Têxtil', solution: 'Vivência "Destrave" com Acelerador de Vendas na convenção, prospecção real medida durante o game', results: ['84 prospecções durante o game', 'NPS 90'] },
    { id: 'C5', client: 'Piracanjuba', segment: 'Alimentos', solution: 'Convenção de vendas gamificada com Negocialipse', results: ['NPS 90 nas convenções gamificadas'] },
    { id: 'C6', client: 'Sem Parar Empresas', segment: 'Serviços', solution: 'Vendópolis e Negocialipse para simular carteira, prospecção e decisão', results: ['98,9% de aprovação'] },
    { id: 'C7', client: 'Sicredi', segment: 'Cooperativismo / Crédito', solution: 'Desenvolvimento comercial e Mapa de Relacionamento Comercial, modelo replicável nas agências', results: ['modelo replicável conectando propósito e produtividade'] },
    { id: 'C8', client: 'Atlas Copco', segment: 'Indústria', solution: 'Padronização da gestão de distribuidores e governança comercial', results: ['governança de canais em curso'] },
    { id: 'C9', client: 'TIMAC Latam Sur', segment: 'Agro / América Latina', solution: 'Playbooks de vendas e liderança para Paraguai, Uruguai e Argentina', results: ['operação em PY, UY e AR'] } ],
  markets: { segments: ['Agronegócio', 'Cooperativas', 'Indústria', 'Distribuição', 'Varejo', 'Tecnologia', 'Financeiro', 'Serviços', 'Consórcios', 'Farma', 'Imobiliário'], models: ['B2B consultivo', 'Equipes externas', 'Inside sales', 'Representantes', 'Canais e distribuidores', 'Franquias', 'Multiunidades', 'Venda recorrente', 'Venda técnica'], challenges: ['Baixa previsibilidade', 'Liderança fraca', 'Falta de processo', 'Escalar canais', 'CRM subutilizado', 'Baixa conversão', 'Dependência de pessoas-chave'] },
  content_channels: ['Radar VendaMais (newsletter, segunda)', 'E-zine VendaMais / E-zine do Raul (terça)', 'Podcast VendaMais (quinta, YouTube e Spotify, 169+ episódios)', 'Blog vendamais.com.br', 'LinkedIn grupo-vendamais', 'Instagram @grupo.vendamais'],
  editorial_territories: ['Proteção de margem e o custo do desconto', 'Previsibilidade, funil, forecast, indicador e rotina de gestão', 'Liderança comercial, formação de líder e sucessão', 'Política comercial, alçadas e governança', 'CRM que orienta decisão', 'Gestão de canais, representantes e distribuidores', 'Treinamento que vira comportamento; sustentação pós-treino', 'Convenções com objetivo comercial e games', 'IA aplicada a vendas e prática diária do vendedor', 'Dependência de pessoas-chave e BPO', 'Venda consultiva, cliente indeciso e aceleração de decisão'],
  anti_persona: 'Empresa pequena (menos de 10 pessoas em vendas) que quer palestra motivacional para animar o time. Não é o perfil.',
  contact: { cta_url: 'https://vendamais.com.br/contato-2/', whatsapp: '(41) 99239-0796', email: 'atendimento@vendamais.com.br' }
};
// Converte o conhecimento em evidências rastreáveis (ids K*) para a camada de QA.
export function knowledgeEvidence(k = KNOWLEDGE_V1) {
  const ev = [];
  k.proof_numbers.forEach(p => ev.push({ id: `K-${p.id}`, kind: p.number ? 'number' : 'fact', text: p.text, source_id: 'kb_vendamais', strength: 'alta' }));
  k.cases.forEach(c => ev.push({ id: `K-${c.id}`, kind: 'example', text: `${c.client} (${c.segment}): ${c.solution}. Resultados: ${c.results.join('; ')}`, source_id: 'kb_vendamais', strength: 'alta' }));
  k.fronts.forEach(f => ev.push({ id: `K-${f.id}`, kind: 'fact', text: `${f.name}: ${f.promise} Ofertas: ${f.offers.join(', ')}. Problemas que resolve: ${f.problems.join('; ')}.`, source_id: 'kb_vendamais', strength: 'alta' }));
  ev.push({ id: 'K-metodo', kind: 'fact', text: `${k.methodology.name}: ${k.methodology.steps.join(' | ')}`, source_id: 'kb_vendamais', strength: 'alta' });
  return ev;
}
export function knowledgeSummary(k = KNOWLEDGE_V1) {
  return `POSICIONAMENTO: ${k.positioning}\nTESE: ${k.thesis}\nPROVAS: ${k.proof_numbers.map(p => p.text).join('; ')}\nFRENTES: ${k.fronts.map(f => `${f.name} (${f.offers.slice(0, 4).join(', ')}...)`).join(' | ')}\nMETODOLOGIA: ${k.methodology.steps.map(s => s.split(':')[0]).join(' > ')}\nTERRITÓRIOS EDITORIAIS: ${k.editorial_territories.join('; ')}\nMERCADOS: ${k.markets.segments.join(', ')}. Desafios: ${k.markets.challenges.join(', ')}\nANTI-PERSONA: ${k.anti_persona}`;
}
