// Newsletter 21 (VendaMais Radar, 23/09/2026): revisão editorial da edição existente + posts derivados PT/ES.
// Aplicada uma vez pela migração applyNewsletter21(). Não altera newsletters anteriores; a versão antiga fica no histórico.
export const N21_CONTENT = {
  thesis: 'Mais oportunidades não corrigem uma operação comercial ineficiente',
  subject: 'Mais oportunidades não corrigem uma operação ineficiente',
  preheader: 'Antes de gerar mais leads, descubra onde sua operação comercial está perdendo resultado.',
  headline: 'Quando a eficiência comercial engole as oportunidades',
  support_line: 'Gerar mais leads não resolve uma operação que perde eficiência ao longo do processo comercial.',
  intro: 'O resultado não vem. A conclusão é quase automática: faltam leads. A empresa aumenta a mídia, contrata prospecção, coloca mais oportunidades no funil.\n\nSó que ninguém parou para verificar onde a operação perde eficiência. A abordagem demora, a qualificação falha, a proposta sai sem condução, o follow-up some. Mais volume entra no mesmo funil e sai pelo mesmo ralo.\n\nAntes de aumentar o topo, descubra onde você já está desperdiçando as oportunidades que tem. Pode ser que o problema que você tenta resolver não seja o problema que você tem.',
  sections: [
    { label: 'O PROBLEMA CENTRAL', title: 'O gargalo raramente está na entrada', body: 'Quando a conversão é baixa, gerar mais leads amplia o desperdício. A ineficiência passa a custar mais caro, porque agora ela processa mais volume.\n\nO gargalo pode estar em pontos diferentes da operação, e cada um deles pede uma resposta diferente:\n\nDemora no primeiro contato. Qualificação inadequada. Baixa compreensão da necessidade do cliente. Propostas enviadas sem condução. Follow-ups inconsistentes. Negócios sem próximo passo definido. Oportunidades esquecidas no CRM. Gestão que acompanha só o volume. Indicadores que ninguém revisa.\n\nNenhum desses pontos se resolve com mais leads. Todos eles se resolvem com diagnóstico, decisão e rotina.', evidence_ids: [] }
  ],
  practical_block: { label: 'DIAGNÓSTICO DE 30 MINUTOS', title: 'Onde a operação está perdendo', intro: 'Abra o CRM ou a planilha de oportunidades dos últimos 90 dias e responda com números. Não precisa de relatório: precisa de honestidade.', steps: [
    { title: 'Quantas oportunidades entraram', text: 'O volume total do período. É a base para todas as contas seguintes.' },
    { title: 'Quantas receberam contato', text: 'Oportunidade que entrou e não recebeu contato é desperdício puro, antes de qualquer conversa sobre conversão.' },
    { title: 'Quanto tempo levou o primeiro contato', text: 'Tempo médio entre a entrada e a primeira abordagem real. Horas e dias, não impressões.' },
    { title: 'Quantas avançaram de etapa', text: 'Conte por etapa. A queda entre uma fase e a seguinte mostra onde o funil perde velocidade.' },
    { title: 'Quantas têm próximo passo definido', text: 'Data, ação e responsável registrados. Sem isso, a oportunidade não está em andamento: está esperando.' },
    { title: 'Quantas estão paradas', text: 'Sem movimentação há mais de 30 dias. Esse número costuma surpreender.' },
    { title: 'Em qual etapa ocorre a maior perda', text: 'Compare as taxas de passagem. A etapa com a maior queda é a candidata a gargalo prioritário.' },
    { title: 'Quantas foram perdidas por falta de acompanhamento', text: 'Separe o que o cliente recusou do que a operação abandonou. São problemas diferentes.' } ] },
  interpretation: { label: 'COMO INTERPRETAR', title: 'Leia o funil pela velocidade, não pelo volume', items: [
    { title: 'Onde o funil perde velocidade', text: 'Etapa longa demais indica decisão travada, proposta sem condução ou follow-up frouxo. Não indica falta de lead.' },
    { title: 'Onde as oportunidades deixam de avançar', text: 'Se a queda concentra em uma etapa, o problema é local e tratável. Se a queda é uniforme, o problema é de processo ou de gestão.' },
    { title: 'Quais comportamentos se repetem', text: 'Abra dez negócios perdidos e procure o padrão: mesma objeção, mesmo atraso, mesma ausência de próximo passo. Padrão é gargalo; exceção é ruído.' },
    { title: 'Qual gargalo pesa mais na receita', text: 'Multiplique a perda de cada etapa pelo ticket médio que passa por ela. O maior número é a prioridade, mesmo que não seja o mais visível.' } ] },
  action: { label: 'AÇÃO RECOMENDADA', title: 'Um gargalo, uma ação, um responsável, um indicador, um prazo', steps: [
    { title: 'Escolha um único gargalo', text: 'O de maior impacto na receita, não o mais confortável de atacar. Resista à lista de dez iniciativas.' },
    { title: 'Defina uma ação observável', text: 'Algo que se vê acontecendo na semana: primeiro contato em até 24 horas, próximo passo registrado em toda oportunidade, revisão de propostas paradas às segundas.' },
    { title: 'Nomeie um responsável', text: 'Uma pessoa, não uma área. Quem responde pelo indicador na reunião comercial.' },
    { title: 'Fixe um indicador e um prazo', text: 'Um número que prova a mudança e 30 dias para medir. Depois disso, o próximo gargalo.' } ] },
  common_error: { label: 'ERROS MAIS COMUNS', title: 'Começar pela solução', body: 'Contratar treinamento, trocar o CRM, aumentar o tráfego ou cobrar mais volume antes de entender onde a operação perde.\n\nOutros erros que se repetem: aumentar a geração de leads sem olhar a conversão; acompanhar só o volume do funil; não registrar o próximo passo; confundir atividade com avanço comercial; tentar resolver todos os gargalos ao mesmo tempo.' },
  meeting_questions: { label: 'LEVE PARA A PRÓXIMA REUNIÃO COMERCIAL', title: 'Seis perguntas para a equipe responder com números', questions: [
    'Onde estamos perdendo mais oportunidades?', 'Em qual etapa o funil perde velocidade?', 'Quais oportunidades estão paradas e por quê?', 'Quantos negócios possuem próximo passo definido?', 'O problema está na quantidade de oportunidades ou na capacidade de convertê-las?', 'Qual gargalo, se resolvido agora, teria maior impacto na receita?' ] },
  question_of_week: { label: 'PERGUNTA DA SEMANA', text: 'Se você resolvesse apenas um gargalo comercial nos próximos 30 dias, qual teria maior impacto na receita?' },
  vendamais_note: 'A VendaMais existe para isso: transformar operação comercial em método, rotina e resultado, do diagnóstico à execução. Vendas levadas a sério.',
  closing: 'Mais leads podem esperar um mês. Uma operação que perde o que já tem, não.',
  cta: { label: 'Vamos conversar sobre onde sua operação está perdendo eficiência?', url: 'https://vendamais.com.br/contato-2/', type: 'diagnostico', helper: 'Fale com a VendaMais ou agende um diagnóstico comercial. A conversa chega diretamente a Fabiano Silva.' },
  podcast: { enabled: true, title: 'Diagnóstico comercial: por onde começar', description: 'Aprofunde o tema desta edição no Podcast VendaMais.', youtube_url: 'https://www.youtube.com/@vendamais', spotify_url: '' },
  claims: [], sources_used: []
};

// Posts derivados. PT aprovado primeiro; ES é adaptação de sentido (contexto Paraguai e América Latina), aguardando validação do Valcir.
const TAGS_PT = ['VendaMais', 'GestãoComercial', 'Vendas', 'EficiênciaComercial'];
const TAGS_ES = ['VendaMais', 'GestiónComercial', 'Ventas', 'EficienciaComercial'];
export const N21_POSTS = {
  training: {
    pt: { kicker: 'EDUCAÇÃO CORPORATIVA', headline: 'Treinar o time antes de saber onde ele perde é gastar duas vezes', support_line: 'Mais leads não corrigem comportamento. Diagnóstico corrige.', proof_number: '', proof_label: '', thesis: 'Treinamento só vira resultado quando ataca o comportamento que trava o funil.', visual_concept: 'Sala de treinamento real, líder de pé diante de um quadro com um funil desenhado à mão, equipe de costas anotando. Luz natural, tons navy.', caption: { hook: 'A equipe recebeu treinamento. O funil continua perdendo nas mesmas etapas. O que aconteceu?', body: 'Quase sempre, o treinamento foi escolhido antes do diagnóstico. Comprou-se técnica de fechamento quando o problema era primeiro contato demorado. Treinou-se negociação quando o problema era proposta enviada sem próximo passo.\n\nComportamento só muda quando o time sabe exatamente onde perde e o gestor acompanha a mudança na rotina, com indicador e prazo. Sem isso, o treinamento vira evento: emociona na sexta, evapora na segunda.\n\nMais oportunidades não corrigem uma operação ineficiente. Mais treinamento genérico também não.', practical_takeaway: 'Antes do próximo programa de desenvolvimento, peça ao comercial um número: em qual etapa do funil a equipe mais perde. Desenhe o treinamento a partir dessa resposta, não do catálogo.', cta: 'Quer conversar sobre como conectar desenvolvimento de equipe ao gargalo real da operação? Fale com a VendaMais.', hashtags: TAGS_PT }, source_claims: [] },
    es: { kicker: 'EDUCACIÓN CORPORATIVA', headline: 'Capacitar al equipo sin saber dónde pierde es pagar dos veces', support_line: 'Más leads no corrigen comportamientos. El diagnóstico sí.', proof_number: '', proof_label: '', thesis: 'La capacitación se convierte en resultado cuando ataca el comportamiento que frena el embudo.', visual_concept: 'Sala de capacitación real, líder frente a una pizarra con un embudo dibujado a mano, equipo tomando notas. Luz natural, tonos navy.', caption: { hook: 'El equipo recibió capacitación. El embudo sigue perdiendo en las mismas etapas. ¿Qué pasó?', body: 'Casi siempre, la capacitación se eligió antes del diagnóstico. Se compró técnica de cierre cuando el problema era el primer contacto tardío. Se entrenó negociación cuando el problema era la propuesta enviada sin próximo paso.\n\nEl comportamiento cambia cuando el equipo sabe exactamente dónde pierde y el gerente acompaña ese cambio en la rutina, con indicador y plazo. Sin eso, la capacitación es un evento: entusiasma el viernes y se diluye el lunes.\n\nMás oportunidades no corrigen una operación ineficiente. Más capacitación genérica, tampoco.', practical_takeaway: 'Antes del próximo programa de desarrollo, pida al área comercial un dato: en qué etapa del embudo el equipo pierde más. Diseñe la capacitación a partir de esa respuesta, no del catálogo.', cta: '¿Conversamos sobre cómo conectar el desarrollo del equipo con el cuello de botella real de su operación? Hable con VendaMais.', hashtags: TAGS_ES }, source_claims: [] }
  },
  consulting: {
    pt: { kicker: 'GESTÃO COMERCIAL', headline: 'Mais leads no mesmo funil só aumentam o desperdício', support_line: 'Antes de investir no topo, meça onde a operação perde velocidade.', proof_number: '', proof_label: '', thesis: 'Gestão comercial começa por localizar o gargalo, não por ampliar o volume.', visual_concept: 'Mesa de decisão com três executivos analisando um painel impresso de indicadores, um deles apontando uma etapa específica. Ambiente sóbrio, luz lateral.', caption: { hook: 'Se a conversão está baixa, dobrar os leads dobra o desperdício. A conta é simples e quase ninguém faz.', body: 'A decisão mais comum quando a meta não vem é aumentar o topo do funil. É a mais cara e a menos precisa. Ela ignora que a operação pode estar perdendo em pontos que nenhum lead novo resolve: primeiro contato lento, qualificação frouxa, proposta sem condução, follow-up inconsistente, negócios sem próximo passo.\n\nUm diagnóstico de 30 minutos no CRM responde o essencial: quantas oportunidades entraram, quantas receberam contato, quantas avançaram, quantas estão paradas e em qual etapa está a maior perda.\n\nCom essa resposta, a decisão muda de "quanto investir em mídia" para "qual gargalo resolver primeiro". Mais oportunidades não corrigem uma operação comercial ineficiente.', practical_takeaway: 'Na próxima reunião comercial, troque a pergunta "quantos leads entraram" por "em qual etapa perdemos mais e quantos negócios têm próximo passo definido".', cta: 'Vamos conversar sobre onde a sua operação está perdendo eficiência? Fale com a VendaMais e agende um diagnóstico comercial.', hashtags: TAGS_PT }, source_claims: [] },
    es: { kicker: 'GESTIÓN COMERCIAL', headline: 'Más leads en el mismo embudo solo multiplican el desperdicio', support_line: 'Antes de invertir en la parte alta, mida dónde la operación pierde velocidad.', proof_number: '', proof_label: '', thesis: 'La gestión comercial empieza por ubicar el cuello de botella, no por ampliar el volumen.', visual_concept: 'Mesa de decisión con tres ejecutivos analizando un tablero impreso de indicadores, uno señala una etapa específica. Ambiente sobrio, luz lateral.', caption: { hook: 'Si la conversión es baja, duplicar los leads duplica el desperdicio. La cuenta es simple y casi nadie la hace.', body: 'La decisión más frecuente cuando la meta no llega es ampliar la parte alta del embudo. Es la más cara y la menos precisa. Ignora que la operación puede estar perdiendo en puntos que ningún lead nuevo resuelve: primer contacto lento, calificación débil, propuesta sin seguimiento, negocios sin próximo paso.\n\nUn diagnóstico de 30 minutos en el CRM responde lo esencial: cuántas oportunidades entraron, cuántas recibieron contacto, cuántas avanzaron, cuántas están detenidas y en qué etapa está la mayor pérdida.\n\nCon esa respuesta, la decisión cambia de "cuánto invertir en medios" a "qué cuello de botella resolver primero". Más oportunidades no corrigen una operación comercial ineficiente.', practical_takeaway: 'En la próxima reunión comercial, cambie la pregunta "cuántos leads entraron" por "en qué etapa perdemos más y cuántos negocios tienen próximo paso definido".', cta: '¿Conversamos sobre dónde su operación está perdiendo eficiencia? Hable con VendaMais y agende un diagnóstico comercial.', hashtags: TAGS_ES }, source_claims: [] }
  },
  business: {
    pt: { kicker: 'VENDAMAIS', headline: 'O problema que você está resolvendo pode não ser o que você tem', support_line: 'Estratégia, pessoas, processo e gestão perdem juntos quando ninguém mede onde o funil vaza.', proof_number: '', proof_label: '', thesis: 'Eficiência comercial é resultado do sistema inteiro, não de um lead a mais.', visual_concept: 'Corredor de operação comercial ao fim do dia, uma pessoa de perfil olhando um quadro grande com o funil e post-its, luz baixa e quente contra fundo navy.', caption: { hook: 'Falta de oportunidades ou perda de eficiência? A maioria das empresas responde antes de medir.', body: 'Quando o resultado não vem, a resposta padrão é gerar mais demanda. Mas oportunidade desperdiçada é um problema de sistema: a estratégia define o cliente errado, a equipe demora no primeiro contato, o processo não exige próximo passo, a gestão acompanha volume e não velocidade, a ferramenta registra e não orienta.\n\nCada uma dessas peças esconde parte da perda. Nenhuma delas se corrige com mais leads.\n\nA pergunta que muda a conversa na diretoria é outra: se resolvêssemos um único gargalo nos próximos 30 dias, qual teria maior impacto na receita? Mais oportunidades não corrigem uma operação comercial ineficiente.', practical_takeaway: 'Reúna comercial, marketing, RH e operação por 30 minutos com um único objetivo: localizar a etapa em que o funil mais perde e nomear um responsável por ela.', cta: 'Quer olhar a sua operação comercial por inteiro, da estratégia à execução? Vamos conversar. Fale com a VendaMais.', hashtags: TAGS_PT }, source_claims: [] },
    es: { kicker: 'VENDAMAIS', headline: 'El problema que está resolviendo puede no ser el que tiene', support_line: 'Estrategia, personas, proceso y gestión pierden juntos cuando nadie mide dónde se escapa el embudo.', proof_number: '', proof_label: '', thesis: 'La eficiencia comercial es resultado de todo el sistema, no de un lead más.', visual_concept: 'Pasillo de una operación comercial al final del día, una persona de perfil mira un tablero grande con el embudo y notas adhesivas, luz baja y cálida sobre fondo navy.', caption: { hook: '¿Falta de oportunidades o pérdida de eficiencia? La mayoría de las empresas responde antes de medir.', body: 'Cuando el resultado no llega, la respuesta habitual es generar más demanda. Pero la oportunidad desperdiciada es un problema de sistema: la estrategia define al cliente equivocado, el equipo tarda en el primer contacto, el proceso no exige próximo paso, la gestión mira volumen y no velocidad, la herramienta registra pero no orienta.\n\nCada una de esas piezas esconde parte de la pérdida. Ninguna se corrige con más leads.\n\nLa pregunta que cambia la conversación en el directorio es otra: si resolviéramos un solo cuello de botella en los próximos 30 días, ¿cuál tendría mayor impacto en los ingresos? Más oportunidades no corrigen una operación comercial ineficiente.', practical_takeaway: 'Reúna a comercial, marketing, RRHH y operaciones durante 30 minutos con un único objetivo: ubicar la etapa donde el embudo pierde más y nombrar un responsable.', cta: '¿Quiere mirar su operación comercial completa, de la estrategia a la ejecución? Conversemos. Hable con VendaMais.', hashtags: TAGS_ES }, source_claims: [] }
  }
};

// Migração idempotente. Retorna true se aplicou.
export function applyNewsletter21(db, { uid, now, audit }) {
  if (db.migrations?.n21) return false;
  const ed = db.editions.find(e => e.id === 'ed_piloto') || db.editions.find(e => /oportunidades|efici[êe]ncia/i.test(e.theme || ''));
  if (!ed) return false;
  ed.brief.number = 21; ed.brief.edition_date = '2026-09-23'; ed.edition_date = '2026-09-23';
  ed.title = 'Newsletter 21 · Quando a eficiência comercial engole as oportunidades'; ed.brief.title = ed.title; ed.theme = 'Quando a eficiência comercial engole as oportunidades'; ed.brief.theme = ed.theme;
  ed.brief.cta = N21_CONTENT.cta.label; ed.brief.cta_type = 'diagnostico'; ed.brief.audience = 'CEO/dono'; ed.brief.tone = 'provocativo';
  const vs = db.newsletter_versions.filter(v => v.edition_id === ed.id).sort((a, b) => a.n - b.n); const prev = vs[vs.length - 1];
  const content = JSON.parse(JSON.stringify(N21_CONTENT));
  if (prev?.content_json?.podcast) { const pp = prev.content_json.podcast; content.podcast = { ...content.podcast, title: pp.title || content.podcast.title, youtube_url: pp.youtube_url || pp.url || content.podcast.youtube_url, spotify_url: pp.spotify_url || '', cover_url: pp.cover_url || '' }; }
  if (prev?.content_json?.cta?.url) content.cta.url = prev.content_json.cta.url;
  if (prev?.content_json?.events) content.events = prev.content_json.events;
  vs.forEach(v => v.is_approved = false);
  const v = { id: uid('nlv'), edition_id: ed.id, n: (prev?.n || 0) + 1, content_json: content, meta: { locks: {}, edited: {}, mode: 'editorial' }, origin: 'human', score: null, qa_json: null, is_approved: true, approved_at: now(), created_at: now(), note: 'Revisão editorial: Newsletter 21 (título, tese, tom, estrutura)' };
  db.newsletter_versions.push(v);
  for (const angle of ['training', 'consulting', 'business']) {
    const src = N21_POSTS[angle]; let p = db.posts.find(x => x.edition_id === ed.id && x.angle === angle);
    const pt = { angle, brief: null, format_reason: '', thesis: src.pt.thesis, headline: src.pt.headline, support_line: src.pt.support_line, proof_number: '', proof_label: '', visual_concept: src.pt.visual_concept, image_prompt: p?.content_json?.image_prompt || '', negative_space: 'bottom', template_id: p?.template_id || '', kicker: src.pt.kicker, caption: src.pt.caption, source_claims: [] };
    const es = { ...pt, headline: src.es.headline, support_line: src.es.support_line, thesis: src.es.thesis, visual_concept: src.es.visual_concept, kicker: src.es.kicker, caption: src.es.caption };
    if (p) { p.versions = p.versions || []; p.versions.push({ content_json: JSON.parse(JSON.stringify(p.content_json)), at: p.updated_at || p.created_at, origin: 'pre-n21' }); p.content_json = pt; p.content_es = es; p.es_status = 'pending_validation'; p.status = 'draft'; p.score = null; p.qa_json = null; p.format = 'single'; p.updated_at = now(); p.meta = p.meta || { locks: {}, edited: {} }; p.meta.edited = {}; }
    else db.posts.push({ id: uid('post'), edition_id: ed.id, angle, content_json: pt, content_es: es, es_status: 'pending_validation', template_id: { training: 'T01', consulting: 'T06', business: 'T03' }[angle], image_id: null, crop: { scale: 1, x: 0.5, y: 0.5 }, partner_id: null, format: 'single', status: 'draft', score: null, qa_json: null, origin: 'human', meta: { locks: {}, edited: {} }, versions: [], created_at: now(), updated_at: now() });
  }
  ed.status = 'posts_generated'; ed.updated_at = now();
  const br = db.brand_rules.find(r => r.active) || db.brand_rules[0]; if (br?.rules_json?.newsletter) br.rules_json.newsletter.name = 'VendaMais Radar';
  db.settings.last_edition_number = Math.max(db.settings.last_edition_number || 0, 21);
  db.migrations = { ...(db.migrations || {}), n21: now() };
  audit('migration.n21', 'edition', ed.id, { version: v.n });
  return true;
}
